project:
  type: manuscript

manuscript:
  article: index.qmd

format:
  html:
    toc: true
    comments:
      hypothesis: true
  docx: default
  jats: default
  arxiv-pdf:
    keep-tex: true
    cite-method: natbib
    linenumbers: true
    runninghead: "initial submission"
    authorcols: true
notebook-links: global

execute:
  freeze: auto


